"""
Markdown report generator — assembles the final output document.

Sections produced (in order):
  1. Header — project name, timestamp, total issue count
  2. Summary table — counts per severity level
  3. Overview table — one row per issue with location + confidence
  4. Detailed findings — full issue blocks grouped by severity
  5. File breakdown — per-file issue counts sorted by density
  6. Footer — attribution

All inputs are sorted by severity (Critical → Info) before rendering.
"""

from datetime import datetime

from src.issues.schema import Issue
from src.issues.scoring import (
    sort_by_severity,
    group_by_file,
    group_by_severity,
    get_summary_stats,
)
from src.report.formatter import format_issue_block, format_issue_summary_row
from src.utils.logger import get_logger

logger = get_logger(__name__)


class MarkdownReportGenerator:
    """
    Converts a list of validated Issue objects into a Markdown report string.
    Each section is generated by a private method and joined at the end.
    """

    def __init__(self, project_name: str = "Codebase"):
        self._project_name = project_name

    def generate(self, issues: list[Issue]) -> str:
        """
        Build the complete report and return it as a Markdown string.
        Issues are sorted once at the top; all sections use the sorted order.
        """
        sorted_issues = sort_by_severity(issues)
        stats = get_summary_stats(sorted_issues)

        sections: list[str] = [
            self._build_header(stats),
            self._build_summary(stats),
        ]

        if sorted_issues:
            sections.append(self._build_issue_table(sorted_issues))
            sections.append(self._build_detailed_issues(sorted_issues))
            sections.append(self._build_file_breakdown(sorted_issues))

        sections.append(self._build_footer())

        report = "\n".join(sections)
        logger.info(f"Report generated: {len(sorted_issues)} issues")
        return report

    def _build_header(self, stats: dict[str, int]) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        return (
            f"# 🔍 CodeSage Analysis Report\n\n"
            f"**Project:** {self._project_name}  \n"
            f"**Generated:** {now}  \n"
            f"**Total Issues:** {stats['total']}  \n\n"
        )

    def _build_summary(self, stats: dict[str, int]) -> str:
        return (
            "## 📊 Summary\n\n"
            "| Severity | Count |\n"
            "|----------|-------|\n"
            f"| 🔴 Critical | {stats['critical']} |\n"
            f"| 🟠 High | {stats['high']} |\n"
            f"| 🟡 Medium | {stats['medium']} |\n"
            f"| 🔵 Low | {stats['low']} |\n"
            f"| ⚪ Info | {stats['info']} |\n"
            f"| ✅ Validated | {stats['validated']} |\n\n"
        )

    def _build_issue_table(self, issues: list[Issue]) -> str:
        lines = [
            "## 📋 Issues Overview\n",
            "| # | Severity | Title | Location | Confidence |",
            "|---|----------|-------|----------|------------|",
        ]
        for idx, issue in enumerate(issues, 1):
            lines.append(format_issue_summary_row(issue, idx))
        lines.append("\n")
        return "\n".join(lines)

    def _build_detailed_issues(self, issues: list[Issue]) -> str:
        lines = ["## 🔎 Detailed Findings\n"]
        by_severity = group_by_severity(issues)
        severity_order = ["critical", "high", "medium", "low", "info"]
        global_index = 1

        for sev in severity_order:
            group = by_severity.get(sev, [])
            if not group:
                continue

            lines.append(f"\n### {sev.upper()} Issues ({len(group)})\n")
            for issue in group:
                lines.append(format_issue_block(issue, global_index))
                global_index += 1

        return "\n".join(lines)

    def _build_file_breakdown(self, issues: list[Issue]) -> str:
        by_file = group_by_file(issues)
        # Sort files so the most issue-dense ones appear first
        sorted_files = sorted(by_file.items(), key=lambda x: len(x[1]), reverse=True)

        lines = [
            "## 📁 File Breakdown\n",
            "| File | Issues |",
            "|------|--------|",
        ]
        for file_path, file_issues in sorted_files:
            lines.append(f"| `{file_path}` | {len(file_issues)} |")
        lines.append("\n")
        return "\n".join(lines)

    def _build_footer(self) -> str:
        return (
            "---\n\n"
            "*Generated by [CodeSage](https://github.com/entropy/codesage) — "
            "AI-powered codebase analysis tool.*\n"
        )
